//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto3Capas.WSInsServicios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSInsServicios.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name InsertarServicioResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarServicio", ReplyAction="*")]
        Proyecto3Capas.WSInsServicios.InsertarServicioResponse InsertarServicio(Proyecto3Capas.WSInsServicios.InsertarServicioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarServicio", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto3Capas.WSInsServicios.InsertarServicioResponse> InsertarServicioAsync(Proyecto3Capas.WSInsServicios.InsertarServicioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarServicioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarServicio", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto3Capas.WSInsServicios.InsertarServicioRequestBody Body;
        
        public InsertarServicioRequest() {
        }
        
        public InsertarServicioRequest(Proyecto3Capas.WSInsServicios.InsertarServicioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarServicioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double Karaoke;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double Licores;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double ValetParking;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double Dj;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double Payaso;
        
        public InsertarServicioRequestBody() {
        }
        
        public InsertarServicioRequestBody(double Karaoke, double Licores, double ValetParking, double Dj, double Payaso) {
            this.Karaoke = Karaoke;
            this.Licores = Licores;
            this.ValetParking = ValetParking;
            this.Dj = Dj;
            this.Payaso = Payaso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarServicioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarServicioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto3Capas.WSInsServicios.InsertarServicioResponseBody Body;
        
        public InsertarServicioResponse() {
        }
        
        public InsertarServicioResponse(Proyecto3Capas.WSInsServicios.InsertarServicioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarServicioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarServicioResult;
        
        public InsertarServicioResponseBody() {
        }
        
        public InsertarServicioResponseBody(string InsertarServicioResult) {
            this.InsertarServicioResult = InsertarServicioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Proyecto3Capas.WSInsServicios.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Proyecto3Capas.WSInsServicios.WebServiceSoap>, Proyecto3Capas.WSInsServicios.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto3Capas.WSInsServicios.InsertarServicioResponse Proyecto3Capas.WSInsServicios.WebServiceSoap.InsertarServicio(Proyecto3Capas.WSInsServicios.InsertarServicioRequest request) {
            return base.Channel.InsertarServicio(request);
        }
        
        public string InsertarServicio(double Karaoke, double Licores, double ValetParking, double Dj, double Payaso) {
            Proyecto3Capas.WSInsServicios.InsertarServicioRequest inValue = new Proyecto3Capas.WSInsServicios.InsertarServicioRequest();
            inValue.Body = new Proyecto3Capas.WSInsServicios.InsertarServicioRequestBody();
            inValue.Body.Karaoke = Karaoke;
            inValue.Body.Licores = Licores;
            inValue.Body.ValetParking = ValetParking;
            inValue.Body.Dj = Dj;
            inValue.Body.Payaso = Payaso;
            Proyecto3Capas.WSInsServicios.InsertarServicioResponse retVal = ((Proyecto3Capas.WSInsServicios.WebServiceSoap)(this)).InsertarServicio(inValue);
            return retVal.Body.InsertarServicioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto3Capas.WSInsServicios.InsertarServicioResponse> Proyecto3Capas.WSInsServicios.WebServiceSoap.InsertarServicioAsync(Proyecto3Capas.WSInsServicios.InsertarServicioRequest request) {
            return base.Channel.InsertarServicioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto3Capas.WSInsServicios.InsertarServicioResponse> InsertarServicioAsync(double Karaoke, double Licores, double ValetParking, double Dj, double Payaso) {
            Proyecto3Capas.WSInsServicios.InsertarServicioRequest inValue = new Proyecto3Capas.WSInsServicios.InsertarServicioRequest();
            inValue.Body = new Proyecto3Capas.WSInsServicios.InsertarServicioRequestBody();
            inValue.Body.Karaoke = Karaoke;
            inValue.Body.Licores = Licores;
            inValue.Body.ValetParking = ValetParking;
            inValue.Body.Dj = Dj;
            inValue.Body.Payaso = Payaso;
            return ((Proyecto3Capas.WSInsServicios.WebServiceSoap)(this)).InsertarServicioAsync(inValue);
        }
    }
}
